-- Kisan-Setu Final BCA Project - Supabase Database Setup
-- Supabase -> SQL Editor -> New Query -> Paste -> Run

create table if not exists profiles (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    username text not null,
    email text unique not null,
    password text not null,
    role text not null check (role in ('farmer', 'buyer')),
    location text
);

create table if not exists products (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    farmer_id bigint references profiles(id) on delete cascade,
    farmer_name text,
    crop_name text not null,
    category text,
    price numeric not null,
    quantity text not null,
    description text
);

create table if not exists orders (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    buyer_id bigint references profiles(id) on delete cascade,
    buyer_name text,
    product_id bigint references products(id) on delete cascade,
    crop_name text,
    quantity_ordered numeric default 1,
    total_amount numeric,
    payment_method text,
    status text default 'Order Placed'
);

-- For academic prototype/demo only.
alter table profiles disable row level security;
alter table products disable row level security;
alter table orders disable row level security;

insert into profiles (username, email, password, role, location)
values
('Ramesh Farmer', 'farmer@test.com', '1234', 'farmer', 'Nashik'),
('Kashish Buyer', 'buyer@test.com', '1234', 'buyer', 'Kolkata');

insert into products (farmer_id, farmer_name, crop_name, category, price, quantity, description)
values
(1, 'Ramesh Farmer', 'Fresh Tomatoes', 'Vegetables', 55, '1 kg', 'Fresh farm tomatoes directly from Nashik.'),
(1, 'Ramesh Farmer', 'Basmati Rice', 'Grains', 420, '5 kg', 'Premium quality rice for household use.'),
(1, 'Ramesh Farmer', 'Organic Spinach', 'Vegetables', 22, '1 bunch', 'Fresh green spinach from local farms.');
